<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findbyproducttype($product_type, $rowperpage){ 
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
		
		if($product_type == 'all'){
			$qb->select('p')
           ->from('AppBundle:Product', 'p')
		   ->setMaxResults($rowperpage);
		}else{
			$qb->select('p')
			->from('AppBundle:Product', 'p')
			->where('p.producttype = :producttype')
			->setParameter('producttype', $product_type)
			->setMaxResults($rowperpage);
		}
		
        $result = $qb->getQuery()->getResult();
        return $result; 
    }
}
